version: '3.8'
services:
  semaglutidenaionestapp:
    image: ohdsi/glp1diliapp:1.0.0
    env_file: .env
    build:
      context: .
      args:
        APP_NAME: Glp1DiliApp
    ports:
      - "3838:3838"